export const CHANGE_ID = "CHANGE_ID";

export const GET_CAT_IMAGE_FETCH = "GET_CAT_IMAGE_FETCH";
export const GET_CAT_IMAGE_SUCCESS = "GET_CAT_IMAGE_SUCCESS";
export const GET_CAT_IMAGE_ERROR = "GET_CAT_IMAGE_ERROR";

export const GET_CAT_NAME_FETCH = "GET_CAT_NAME_FETCH";
export const GET_CAT_NAME_SUCCESS = "GET_CAT_NAME_SUCCESS";
export const GET_CAT_NAME_ERROR = "GET_CAT_NAME_ERROR";
